### ISSUE TITLE
Chip Authentication failure

### ISSUE THREAD

**Issue by ayushev** [Infineon/mbedtls-optiga-trust-m#2]
Hi, @ayushev 

We have also verified with XMC4800 & Optiga TrustM kit. I have download the code from [here](https://github.com/Infineon/mbedtls-optiga-trust-m). and set the "**AUTH_TEST** " as 1.

Its **failed** to verify **example_authenticate_chip**
> 15 12098 [Echo0] +++++Authentication Test+++++
> 16 12098 [Echo0] >example_authenticate_chip()
> 17 12098 [Echo0] >pal_crypt_init()
> 18 12108 [Echo0] pal_crypt_init: Random number (len=32)
> 19 12130 [Echo0] <pal_crypt_init()
> 20 12130 [Echo0] Read default cert and verify it
> 21 12130 [Echo0] >read_chip_cert()
> 22 12178 [Echo0] mbedtls_x509_crt_verify failed (status=ffffd900)
> 23 12178 [Echo0] Error: verify cert failed. (status=0x3003)
> 24 12178 [Echo0] <example_authenticate_chip()
> 25 12178 [Echo0] Auth done count=1
> 26 12178 [Echo0] +++++Auth Test Completed+++++

[FYI - not changed anything in the code]

_Originally posted by @Darsh-Dev in https://github.com/Infineon/amazon-freertos/issues/9#issuecomment-676509912_

**Comment by ayushev** [comment]
@Darsh-Dev  can you please recursivle update your appnote and check the result once again. It should work now.

**Comment by Darsh-Dev** [comment]
@ayushev  Its working with updated CA and configuration changed
